#* 我的理解是 hydra先依次加载 defaults 的默认配置  然后加载后面的自定义配置
defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  # monitor: "val/acc"
  # mode: "max"
  monitor: "val/spearman"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

# 先关闭早停机制
# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: -1
